RRHH/Models/Employee.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace RRHH.Models
{
    public partial class Employee
    {
        public ulong Id { get; set; }
        public ulong? Idproject { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public decimal? Payrate { get; set; }
        public DateTime? Startdate { get; set; }
        public int? State { get; set; }
    }
}

RRHH/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using RRHH.Filters;
using RRHH.Models;
using RRHH.Models.VM;

namespace RRHH.Controllers
{
    [CustomAuthorize]
    public class EmployeesController : Controller
    {
        private readonly rrhhContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EmployeesController(rrhhContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            try
            {
                List<EmployeesVM> employees = new List<EmployeesVM>();
                var str = HttpContext.Session.GetString("User");
                var SessionUsuario = JsonConvert.DeserializeObject<User>(str);
                if (SessionUsuario.Idrole == 1)
                {
                    var empleados = await _context.Employees.ToListAsync();
                    foreach (var item in empleados)
                    {
                        EmployeesVM vM = new EmployeesVM();
                        vM.Address = item.Address;
                        vM.Email = item.Email;
                        vM.Id = item.Id;
                        vM.Idproject = item.Idproject;
                        vM.LastName = item.LastName;
                        vM.Name = item.Name;
                        vM.Payrate = item.Payrate;
                        vM.project = _context.Projects.Find(item.Idproject).Name;
                        vM.Startdate = item.Startdate;
                        vM.State = item.State;
                        vM.Telephone = item.Telephone;
                        employees.Add(vM);
                    }
                    return View(employees);
                }
                else
                {
                    var empleados = await _context.Employees.Where(x => x.Idproject == SessionUsuario.Idproject).ToListAsync();
                    return View(empleados);
                }
                
            }
            catch (Exception ex)
            {
                var msn = ex.Message;
                throw;
            }

        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            var document = _context.Documents.Where(x => x.IdEmployee == employee.Id).ToList();
            EmployeeDetails details = new EmployeeDetails();
            details.Address = employee.Address;
            details.documents = document;
            details.Email = employee.Email;
            details.Id = employee.Id;
            details.Idproject = employee.Idproject;
            details.LastName = employee.LastName;
            details.Name = employee.Name;
            details.Payrate = employee.Payrate;
            details.Startdate = employee.Startdate;
            details.State = employee.State;
            details.Telephone = employee.Telephone;
            
            return View(details);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {

            var listrol = (from rol in _context.Roles
                           select new SelectListItem()
                           {
                               Text = rol.Name,
                               Value = rol.Idrole.ToString(),
                           }).ToList();
            ViewBag.roles = listrol;

            var Projects = (from rol in _context.Projects
                            select new SelectListItem()
                            {
                                Text = rol.Name,
                                Value = rol.Idproject.ToString(),
                            }).ToList();
            ViewBag.Projects = Projects;
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Idrole,Idproject,Name,LastName,Telephone,Email,Address,Documents,Payrate,Startdate,State")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            var listrol = (from rol in _context.Roles
                           select new SelectListItem()
                           {
                               Text = rol.Name,
                               Value = rol.Idrole.ToString(),
                           }).ToList();
            ViewBag.roles = listrol;

            var Projects = (from rol in _context.Projects
                            select new SelectListItem()
                            {
                                Text = rol.Name,
                                Value = rol.Idproject.ToString(),
                            }).ToList();
            ViewBag.Projects = Projects;
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ulong id, [Bind("Id,Idrole,Idproject,Name,LastName,Telephone,Email,Address,Documents,Payrate,Startdate,State")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(ulong id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(ulong id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }

        public async Task<IActionResult> UploadDocument(ulong idEmployee, IFormFile doc)
        {
            try
            {
                if (doc == null || doc.Length == 0)
                {
                    return Content("File not selected");
                }
                else
                {
                    var employee = await _context.Employees.FindAsync(idEmployee);
                    //Obteniendo el path de la imagen
                    var FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "img/documents/", employee.Id.ToString() + "/");
                    if (!Directory.Exists(FilePath))
                    {
                        Directory.CreateDirectory(FilePath);
                    }
                    var fileExt = System.IO.Path.GetExtension(doc.FileName).Substring(1);
                    var stream = new FileStream(FilePath+ doc.FileName, FileMode.Create);
                    await doc.CopyToAsync(stream);
                    //Agregando docuemtos a la tabla en la BD
                    Document document = new Document();
                    document.IdEmployee = employee.Id;
                    document.Name = doc.FileName;
                    _context.Set<Document>().Add(document);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

                throw;
            }
        }

        public FileResult download(string id ,string name)
        {
            var fileName = name;

RRHH/Views/Employees/Create.cshtml
@model RRHH.Models.Employee
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Idproject" class="control-label"></label>
                <select asp-for="Idproject"
                        class="form-control"
                        asp-items="@(new SelectList(ViewBag.Projects,"Value", "Text"))">
                </select>
                <span asp-validation-for="Idproject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Payrate" class="control-label"></label>
                <input asp-for="Payrate" class="form-control" />
                <span asp-validation-for="Payrate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Startdate" class="control-label"></label>
                <input asp-for="Startdate" class="form-control" />
                <span asp-validation-for="Startdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

RRHH/Views/Employees/Delete.cshtml
@model RRHH.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idproject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idproject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Payrate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Payrate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Startdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Startdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RRHH/Views/Employees/Details.cshtml
@model RRHH.Models.VM.EmployeeDetails

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Idproject)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Idproject)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Payrate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Payrate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Startdate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Startdate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>
</div>
<h4>Document</h4>
<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Document")
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.documents)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.ActionLink("Download", "download", "Employees", new { id = item.IdEmployee.ToString(), name = item.Name })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RRHH/Views/Employees/Edit.cshtml
@model RRHH.Models.Employee

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Idproject" class="control-label"></label>

                <select asp-for="Idproject"
                        class="form-control"
                        asp-items="@(new SelectList(ViewBag.Projects,"Value", "Text"))">
                </select>
                <span asp-validation-for="Idproject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Payrate" class="control-label"></label>
                <input asp-for="Payrate" class="form-control" />
                <span asp-validation-for="Payrate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Startdate" class="control-label"></label>
                <input asp-for="Startdate" class="form-control" />
                <span asp-validation-for="Startdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RRHH/Views/Employees/Index.cshtml
@model IEnumerable<RRHH.Models.VM.EmployeesVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Employees</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.project)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.LastName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Telephone)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Payrate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Startdate)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.project)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telephone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Payrate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Startdate)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                <a href="DocumentModal" data-id="@item.Id" data-toggle="modal" class="open-AddBookDialog">Documents</a> |
                                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="DocumentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form asp-action="UploadDocument" enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Documents</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input id="idEmployee" name="idEmployee" type="hidden" />
                    <div class="form-group">
                        <input id="doc" name="doc" type="file" class="form-control" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-primary" type="submit">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script>
        $(document).on("click", ".open-AddBookDialog", function () {
            var myBookId = $(this).data('id');
            $(".modal-body #idEmployee").val(myBookId);
            // As pointed out in comments,
            // it is unnecessary to have to manually call the modal.
            $('#DocumentModal').modal('show');
        });
    </script>

}