RRHH/Controllers/ExpensesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RRHH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RRHH.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly rrhhContext _context;

        public ExpensesController(rrhhContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Expenses.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Expenses = await _context.Expenses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Expenses == null)
            {
                return NotFound();
            }

            return View(Expenses);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            var Projects = (from rol in _context.Projects
                            select new SelectListItem()
                            {
                                Text = rol.Name,
                                Value = rol.Idproject.ToString(),
                            }).ToList();
            Projects.Insert(0, new SelectListItem() { Text = "Select", Value = "0" });
            ViewBag.Projects = Projects;
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Date,Description,Idproject,Idemployee,Value")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                expense.State = 1;
                _context.Add(expense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(expense);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Expenses = await _context.Expenses.FindAsync(id);
            if (Expenses == null)
            {
                return NotFound();
            }
            return View(Expenses);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ulong id, [Bind("Id,Date,Description,Idproject,Idemployee,Value")] Expense expense)
        {
            if (id != expense.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    expense.Deliverdate = DateTime.Now.Date;
                    _context.Update(expense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpensesExists(expense.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(expense);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expenses = await _context.Expenses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (expenses == null)
            {
                return NotFound();
            }

            return View(expenses);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(ulong id)
        {
            var Expenses = await _context.Expenses.FindAsync(id);
            _context.Expenses.Remove(Expenses);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpensesExists(ulong id)
        {
            return _context.Expenses.Any(e => e.Id == id);
        }
        public async Task<IActionResult> getEmployee(ulong id)
        {
            try
            {
                var employee = await _context.Employees.Where(x => x.Idproject == id).ToListAsync();
                return Json(employee);
            }
            catch (Exception)
            {

                throw;
            }
        }
        public async Task<IActionResult> approvals()
        {
            try
            {
                return View(await _context.Expenses.ToListAsync());
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult EditApprovals(ulong id)
        {
            try
            {
                var stateapruval = (from rol in _context.Stateapruvals
                                select new SelectListItem()
                                {
                                    Text = rol.Name,
                                    Value = rol.Id.ToString(),
                                }).ToList();
                ViewBag.stateapruval = stateapruval;
                return View();
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditApprovals(ulong id, [Bind("Id,Date,Description,Idproject,Idemployee,Value,State,Payday")] Expense expense)
        {
            if (id != expense.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    expense.Deliverdate = DateTime.Now.Date;
                    _context.Update(expense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpensesExists(expense.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(expense);
        }
    }
}

RRHH/Views/Expenses/Create.cshtml
@model RRHH.Models.Expense

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Expense</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idproject" class="control-label"></label>
                <select asp-for="Idproject"
                        class="form-control"
                        asp-items="@(new SelectList(ViewBag.Projects,"Value", "Text"))">
                </select>
                <span asp-validation-for="Idproject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idemployee" class="control-label"></label>
                @*<input asp-for="Idemployee" class="form-control" />*@
                <select id="select-employee" class="form-control">
                    @*<option value="0">Select</option>*@
                    @*<option value="2">Two</option>*@
                </select>
                <span asp-validation-for="Idemployee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="State" class="control-label"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>*@
            @*<div class="form-group">
                    <label asp-for="Deliverdate" class="control-label"></label>
                    <input asp-for="Deliverdate" class="form-control" />
                    <span asp-validation-for="Deliverdate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Payday" class="control-label"></label>
                    <input asp-for="Payday" class="form-control" />
                    <span asp-validation-for="Payday" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<input type="hidden" id="url-getemployee" value="@Url.Action("getEmployee","Expenses")" />
@section Scripts{
    <script>
        $('#Idproject').on('change', function () {
            /*alert(this.value);*/
            var url = $('#url-getemployee').val();
            $.get(url, { id: this.value }, function (data) {
                /*console.log(data);*/
                $('#select-employee').html("");
                $.each(data, function (key, value) {
                    /*console.log(value.idemployee);*/
                    $('#select-employee').append('<option value="' + value.idemployee + '" selected="selected">' + value.name + '</option>');
                });
            });
        });
    </script>
}

RRHH/Views/Expenses/Delete.cshtml
@model RRHH.Models.Expense

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expense</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idproject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idproject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idemployee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idemployee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Value)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deliverdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deliverdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Payday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Payday)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RRHH/Views/Expenses/Details.cshtml
@model RRHH.Models.Expense

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Expense</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idproject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idproject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idemployee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idemployee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Value)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deliverdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deliverdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Payday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Payday)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RRHH/Views/Expenses/Edit.cshtml
@model RRHH.Models.Expense

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Expense</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idproject" class="control-label"></label>
                <input asp-for="Idproject" class="form-control" />
                <span asp-validation-for="Idproject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idemployee" class="control-label"></label>
                <input asp-for="Idemployee" class="form-control" />
                <span asp-validation-for="Idemployee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="Deliverdate" class="control-label"></label>
                <input asp-for="Deliverdate" class="form-control" />
                <span asp-validation-for="Deliverdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Payday" class="control-label"></label>
                <input asp-for="Payday" class="form-control" />
                <span asp-validation-for="Payday" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RRHH/Views/Expenses/EditApprovals.cshtml
@model RRHH.Models.Expense

@{
    ViewData["Title"] = "EditApprovals";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>EditApprovals</h1>

<h4>Expense</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditApprovals">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @*<div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Idproject" class="control-label"></label>
                    <input asp-for="Idproject" class="form-control" />
                    <span asp-validation-for="Idproject" class="text-danger"></span>
                </div>*@
            @*<div class="form-group">
                    <label asp-for="Idemployee" class="control-label"></label>
                    <input asp-for="Idemployee" class="form-control" />
                    <span asp-validation-for="Idemployee" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Value" class="control-label"></label>
                    <input asp-for="Value" class="form-control" />
                    <span asp-validation-for="Value" class="text-danger"></span>
                </div>*@
            @*<div class="form-group">
                    <label asp-for="State" class="control-label"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select asp-for="State"
                        class="form-control"
                        asp-items="@(new SelectList(ViewBag.stateapruval,"Value", "Text"))">
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="Deliverdate" class="control-label"></label>
                    <input asp-for="Deliverdate" class="form-control" />
                    <span asp-validation-for="Deliverdate" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="Payday" class="control-label"></label>
                <input asp-for="Payday" class="form-control" />
                <span asp-validation-for="Payday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RRHH/Views/Expenses/Index.cshtml
@model IEnumerable<RRHH.Models.Expense>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idproject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idemployee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deliverdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payday)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idproject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idemployee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deliverdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Payday)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RRHH/Views/Expenses/approvals.cshtml
@model IEnumerable<RRHH.Models.Expense>

@{
    ViewData["Title"] = "approvals";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>approvals</h1>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idproject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idemployee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deliverdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payday)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idproject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idemployee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deliverdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Payday)
            </td>
            <td>
                <a asp-action="EditApprovals" asp-route-id="@item.Id">Edit</a> |
                @*<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>